[Providers]
Irancell = "https://irancell.ir/o/1001/%D8%A7%DB%8C%D8%B1%D8%A7%D9%86%D8%B3%D9%84-%D8%A8%D8%B3%D8%AA%D9%87-%D9%87%D8%A7%DB%8C-%D8%A7%DB%8C%D9%86%D8%AA%D8%B1%D9%86%D8%AA-%D9%87%D9%85%D8%B1%D8%A7%D9%87"
Rightell = ""
HamrahAval = ""
[Databases]
[Databases.Postgres]
Host = "localhost"
User = "user"
Password = "irnetpackagesPassword#1536"
Name = "iran-net-packages_db"
port = 5432
TimeZone="Asia/Tehran"
[Databases.Test]
Host = "localhost"
User = "user"
Password = "irnetpackagesPassword#1536"
Name = "iran-net-packages_test-db"
port = 9010
TimeZone="Asia/Tehran"